Repeatable hash type flags bugfix.
erikhuda/thor pull request #769
Opened 2022-01-17 19:24 UTC by patrick-motard

They treated like every other type now. Instead of merging each key/val
into a hash, each flag is treated like it's own hash that should be put
into an array.

fixes #768

2022-01-18 14:20 UTC, dorner commented
Nice! Looks good to me - @rafaelfranca ?

2022-12-22 16:00 UTC, wwwbruno commented
Any updates on this fix? I faced this issue and this solves my problem.

2023-05-11 20:07 UTC, rafaelfranca commented
This is a change in the behavior and people might be expecting the option to merge instead of having two hashes. I don't think I can accept this change as is. I totally get the current behavior isn't what you want, but we can't assume it is broken and don't have a way to have it.

I'd accept an option that would allow the behavior you want though.

2023-05-11 23:02 UTC, rafaelfranca requested changes
See above comment

2026-07-17 15:44 UTC, closed without merging